version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: lrmig2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: lrmig2
      DB_USER: postgres
      DB_PASSWORD: postgres
      CONTAINER_CONFIG: /app/config/container_config.yaml
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /home/photos:/data/photos:ro
      - /mnt/backup:/data/backup:ro
      - /mnt/archive:/data/archive:ro
    command: python -m src.scan_cli --help

volumes:
  postgres_data:
