# Target directories for scanning

target_directories:
  # Personal photo directories
  personal:
    - path: /data/photos/personal/2022
      description: "Personal photos 2022"
      category: "P"  # P for Personal
    - path: /data/photos/personal/2023
      description: "Personal photos 2023"
      category: "P"
      
  # Work photo directories
  work:
    - path: /data/photos/work
      description: "Work photos"
      category: "W"  # W for Work
      
  # Backup directories (to be categorized)
  backup:
    - path: /data/backup/lightroom
      description: "External drive backup"
      category: null  # Will be assigned during processing
    - path: /data/archive/old_photos
      description: "Archive photos"
      category: null

# Global scan settings
settings:
  recursive: true
  excluded_patterns:
    - "*StarQ*"
    - "export_*" 